/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Analogies: typeof import('./src/components/Analogies.vue')['default']
    Analogy: typeof import('./src/components/Analogy.vue')['default']
    AppFullpage: typeof import('./src/components/AppFullpage.vue')['default']
    CounterCo2Data: typeof import('./src/components/CounterCo2Data.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    History: typeof import('./src/components/History.vue')['default']
    HistoryStratum: typeof import('./src/components/HistoryStratum.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MiniViz: typeof import('./src/components/MiniViz.vue')['default']
    PeriodPicker: typeof import('./src/components/PeriodPicker.vue')['default']
    Popup: typeof import('./src/components/Popup.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    Statistics: typeof import('./src/components/Statistics.vue')['default']
    Trends: typeof import('./src/components/Trends.vue')['default']
    TypePicker: typeof import('./src/components/TypePicker.vue')['default']
  }
}
